name: Build Docker images

on:
  schedule:
    - cron: '0 0 * * *' # At 00:00.
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  tf2-base:
    runs-on: ubuntu-latest
    outputs:
      tf2-base-version: ${{ steps.docker_meta.outputs.version }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: melkortf/tf2-base
          tags: type=sha,format=long
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./packages/tf2-base
          tags: ${{ steps.docker_meta.outputs.tags }}
          load: true
      -
        name: Save docker image
        run: docker save melkortf/tf2-base:${{ steps.docker_meta.outputs.version }} | gzip > tf2-base.tar.gz
      -
        name: Upload docker image
        uses: actions/upload-artifact@v2
        with:
          name: tf2-base
          path: tf2-base.tar.gz

  tf2-sourcemod:
    runs-on: ubuntu-latest
    needs: tf2-base
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Download tf2-base
        uses: actions/download-artifact@v2
        with:
          name: tf2-base
          path: tf2-base.tar.gz
      - 
        name: Load tf2-base
        run: docker load < tf2-base.tar.gz
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: melkortf/tf2-sourcemod
          tags: type=sha,format=long
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./packages/tf2-sourcemod
          build-args: |
            TF2_BASE_VERSION=${{ needs.tf2-base.outputs.tf2-base-version }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
