name: Build Docker images

on:
  schedule:
    - cron: '0 0 * * *' # At 00:00.
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io

jobs:
  tf2-base:
    runs-on: ubuntu-latest
    outputs:
      tf2-base-tag: ${{ steps.docker_meta.outputs.version }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/melkortf/tf2-base
          tags: type=sha,format=long
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./packages/tf2-base
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: true
          platforms: linux/amd64

  tf2-sourcemod:
    runs-on: ubuntu-latest
    needs: tf2-base
    outputs:
      tf2-sourcemod-tag: ${{ steps.docker_meta.outputs.version }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/melkortf/tf2-sourcemod
          tags: type=sha,format=long
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./packages/tf2-sourcemod
          build-args: |
            TF2_BASE_TAG=${{ needs.tf2-base.outputs.tf2-base-tag }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: true
          platforms: linux/amd64

  tf2-mge:
    runs-on: ubuntu-latest
    needs: tf2-sourcemod
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/melkortf/tf2-mge
          tags: type=sha,format=long
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./packages/tf2-mge
          build-args: |
            TF2_SOURCEMOD_TAG=${{ needs.tf2-sourcemod.outputs.tf2-sourcemod-tag }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: true
          platforms: linux/amd64

  tf2-competitive:
    runs-on: ubuntu-latest
    needs: tf2-sourcemod
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/melkortf/tf2-competitive
          tags: type=sha,format=long
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./packages/tf2-competitive
          build-args: |
            TF2_SOURCEMOD_TAG=${{ needs.tf2-sourcemod.outputs.tf2-sourcemod-tag }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: true
          platforms: linux/amd64

  tf2-dm:
    runs-on: ubuntu-latest
    needs: tf2-sourcemod
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/melkortf/tf2-dm
          tags: type=sha,format=long
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./packages/tf2-dm
          build-args: |
            TF2_SOURCEMOD_TAG=${{ needs.tf2-sourcemod.outputs.tf2-sourcemod-tag }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: true
          platforms: linux/amd64
