name: Update package

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        required: true
        options:
          - metamod
          - sourcemod
          - etf2l_configs
          - f2_sourcemod_plugins
          - tf2-comp-fixes

      version:
        type: string
        required: true

jobs:
  update-package:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace version string
        run: |
          case ${{ inputs.package }} in
            metamod)
              sed -i 's/METAMOD_VERSION_BUILD=.*/METAMOD_VERSION_BUILD=${{ inputs.version }}/' packages/tf2-sourcemod/Dockerfile
              ;;
            sourcemod)
              sed -i 's/SOURCEMOD_VERSION_BUILD=.*/SOURCEMOD_VERSION_BUILD=${{ inputs.version }}/' packages/tf2-sourcemod/Dockerfile
              ;;
            etf2l_configs)
              sed -i 's/ETF2L_CONFIGS_VERSION=.*/ETF2L_CONFIGS_VERSION=${{ inputs.version }}/' packages/tf2-competitive/Dockerfile
              ;;
            f2_sourcemod_plugins)
              sed -i 's/F2_SOURCEMOD_PLUGINS_VERSION=.*/F2_SOURCEMOD_PLUGINS_VERSION=${{ inputs.version }}/' packages/tf2-competitive/Dockerfile
              ;;
            tf2-comp-fixes)
              sed -i 's/COMP_FIXES_PLUGIN_VERSION=.*/COMP_FIXES_PLUGIN_VERSION=${{ inputs.version }}/' packages/tf2-competitive/Dockerfile
              ;;
            *)
              echo "invalid package"
              exit 1
              ;;
          esac

      - name: Download new package version and replace its md5
        run: |
          case ${{ inputs.package }} in
            metamod)
              METAMOD_URL=$(grep -r "ARG METAMOD" packages/tf2-sourcemod/Dockerfile | sed -E 's/^ARG\s(.+)=(.+)$/\1="\2"/g' | { eval "$(cat -)"; echo $METAMOD_TARBALL_URL; })
              MD5SUM=$(wget -O - "$METAMOD_URL" | tee file | md5sum | awk '{print $1}' && rm file)
              METAMOD_TARBALL_FILE_NAME=$(grep -r "ARG METAMOD" packages/tf2-sourcemod/Dockerfile | sed -E 's/^ARG\s(.+)=(.+)$/\1="\2"/g' | { eval "$(cat -)"; echo $METAMOD_TARBALL_FILE_NAME; })
              sed -i -E 's/^([0-9a-f]+)(\s+)(mmsource.*\.tar\.gz)$/'"$MD5SUM"'\2'"$METAMOD_TARBALL_FILE_NAME"'/g' packages/tf2-sourcemod/checksum.md5
              echo "package_url=${METAMOD_URL}" >> "$GITHUB_ENV"
              echo "package_md5=${MD5SUM}" >> "$GITHUB_ENV"
              ;;
            
            sourcemod)
              SOURCEMOD_URL=$(grep -r "ARG SOURCEMOD" packages/tf2-sourcemod/Dockerfile | sed -E 's/^ARG\s(.+)=(.+)$/\1="\2"/g' | { eval "$(cat -)"; echo $SOURCEMOD_TARBALL_URL; })
              MD5SUM=$(wget -O - "$SOURCEMOD_URL" | tee file | md5sum | awk '{print $1}' && rm file)
              SOURCEMOD_TARBALL_FILE_NAME=$(grep -r "ARG SOURCEMOD" packages/tf2-sourcemod/Dockerfile | sed -E 's/^ARG\s(.+)=(.+)$/\1="\2"/g' | { eval "$(cat -)"; echo $SOURCEMOD_TARBALL_FILE_NAME; })
              sed -i -E 's/^([0-9a-f]+)(\s+)(sourcemod.*\.tar\.gz)$/'"$MD5SUM"'\2'"$SOURCEMOD_TARBALL_FILE_NAME"'/g' packages/tf2-sourcemod/checksum.md5
              echo "package_url=${SOURCEMOD_URL}" >> "$GITHUB_ENV"
              echo "package_md5=${MD5SUM}" >> "$GITHUB_ENV"
              ;;

            etf2l_configs)
              ETF2L_CONFIGS_URL=$(grep -r "ARG ETF2L_CONFIGS" packages/tf2-competitive/Dockerfile | sed -E 's/^ARG\s(.+)=(.+)$/\1="\2"/g' | { eval "$(cat -)"; echo $ETF2L_CONFIGS_URL; })
              MD5SUM=$(wget -O - "$ETF2L_CONFIGS_URL" | tee file | md5sum | awk '{print $1}' && rm file)
              sed -i -E 's/^([0-9a-f]+)(\s+)(etf2l_configs.zip)$/'"$MD5SUM"'\2\3/g' packages/tf2-competitive/checksum.md5
              echo "package_url=${ETF2L_CONFIGS_URL}" >> "$GITHUB_ENV"
              echo "package_md5=${MD5SUM}" >> "$GITHUB_ENV"
              ;;
            f2_sourcemod_plugins)
              F2_SOURCEMOD_PLUGINS_URL=$(grep -r "ARG F2_SOURCEMOD_PLUGINS" packages/tf2-competitive/Dockerfile | sed -E 's/^ARG\s(.+)=(.+)$/\1="\2"/g' | { eval "$(cat -)"; echo $F2_SOURCEMOD_PLUGINS_URL; })
              MD5SUM=$(wget -O - "$F2_SOURCEMOD_PLUGINS_URL" | tee file | md5sum | awk '{print $1}' && rm file)
              sed -i -E 's/^([0-9a-f]+)(\s+)(f2-sourcemod-plugins.zip)$/'"$MD5SUM"'\2\3/g' packages/tf2-competitive/checksum.md5
              echo "package_url=${F2_SOURCEMOD_PLUGINS_URL}" >> "$GITHUB_ENV"
              echo "package_md5=${MD5SUM}" >> "$GITHUB_ENV"
              ;;
            tf2-comp-fixes)
              COMP_FIXES_PLUGIN_URL=$(grep -r "ARG COMP_FIXES_PLUGIN" packages/tf2-competitive/Dockerfile | sed -E 's/^ARG\s(.+)=(.+)$/\1="\2"/g' | { eval "$(cat -)"; echo $COMP_FIXES_PLUGIN_URL; })
              MD5SUM=$(wget -O - "$COMP_FIXES_PLUGIN_URL" | tee file | md5sum | awk '{print $1}' && rm file)
              sed -i -E 's/^([0-9a-f]+)(\s+)(tf2-comp-fixes.zip)$/'"$MD5SUM"'\2\3/g' packages/tf2-competitive/checksum.md5
              echo "package_url=${COMP_FIXES_PLUGIN_URL}" >> "$GITHUB_ENV"
              echo "package_md5=${MD5SUM}" >> "$GITHUB_ENV"
              ;;
            *)
              echo "invalid package"
              exit 1
              ;;
          esac

      - name: Generate human-friendly package name
        run: |
          case ${{ inputs.package }} in
            metamod)
              echo "package_name=Metamod:Source" >> "$GITHUB_ENV"
              ;;
            sourcemod)
              echo "package_name=SourceMod" >> "$GITHUB_ENV"
              ;;
            etf2l_configs)
              echo "package_name=ETF2L.org gameserver configs" >> "$GITHUB_ENV"
              ;;
            f2_sourcemod_plugins)
              echo "package_name=F2's SourceMod plugins" >> "$GITHUB_ENV"
              ;;
            tf2-comp-fixes)
              echo "package_name=TF2 Competitive Fixes" >> "$GITHUB_ENV"
              ;;
            *)
              echo "invalid package"
              exit 1
              ;;
          esac

      - name: Generate real package version
        run: |
          case ${{ inputs.package }} in
            metamod)
              METAMOD_VERSION=$(grep -r "ARG METAMOD" packages/tf2-sourcemod/Dockerfile | sed -E 's/^ARG\s(.+)=(.+)$/\1="\2"/g' | { eval "$(cat -)"; echo $METAMOD_VERSION; })
              echo "package_version=${METAMOD_VERSION}" >> "$GITHUB_ENV"
              ;;
            sourcemod)
              SOURCEMOD_VERSION=$(grep -r "ARG SOURCEMOD" packages/tf2-sourcemod/Dockerfile | sed -E 's/^ARG\s(.+)=(.+)$/\1="\2"/g' | { eval "$(cat -)"; echo $SOURCEMOD_VERSION; })
              echo "package_version=${SOURCEMOD_VERSION}" >> "$GITHUB_ENV"
              ;;
            *)
              echo "package_version=${{ inputs.version }}" >> "$GITHUB_ENV"
              ;;
          esac

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "fix(deps): update ${{ env.package_name }} to version ${{ env.package_version }}"
          sign-commits: true
          title: "fix(deps): update ${{ env.package_name }} to version ${{ env.package_version }}"
          body: |
            Update [${{ env.package_name }}](${{ env.package_url }}) to version ${{ env.package_version }}
            MD5: ${{ env.package_md5 }}
          branch: update-${{ inputs.package }}-${{ env.package_version }}
          delete-branch: true
          reviewers: garrappachc
